FROM node:lts-alpine as builder

ENV ENV development
ENV PATH /app/node_modules/.bin:/usr/local/bin:$PATH

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/app/node_modules \
  --mount=type=cache,target=/app/.pnpm-store \
  npm install -g pnpm prisma @angular/cli && \
  chown -R node:node /app

USER node

EXPOSE 4200

ENTRYPOINT ["./docker-entry.sh"]
