version: "3.8"

services:
  webapp:
    container_name: pluma-online
    build:
      context: ./
      dockerfile: Dockerfile-devel
      cache_from:
        - node:lts-alpine
    depends_on:
      - database
      - redis
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
    ports:
      - 4200:4200
    restart: unless-stopped
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
