version: "3.8"

services:
  nginx:
    container_name: pluma-online-nginx
    build:
      context: ./nginx
      cache_from:
        - alpine:latest
        - fiubiorg/nginx:latest
      labels:
        com.pluma-nginx.description: "Custom NGINX container for PluMA Online"
        com.pluma-nginx.maintainer: "Joseph R. Quinn <quinn.josephr@protonmail.com>"
      args:
        - NGINX_VERSION=1.19.10
    image: fiubiorg/nginx:latest
    volumes:
      - web:/src/http
      - ./nginx/etc/nginx:/etc/nginx
      - ./nginx/server-configs-nginx/h5bp:/etc/nginx/h5bp
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - webapp

  database:
    container_name: pluma-online-database
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    container_name: pluma-redis
    image: redis:alpine

  webapp:
    container_name: pluma-online-webapp
    build:
      context: ./
      dockerfile: Dockerfile
      cache_from:
        - node:lts-alpine
      labels:
        com.pluma-backend.description: "Container for PluMA Online"
        com.pluma-backend.maintainer: "Joseph R. Quinn <423821+quinnjr@users.noreply.github.com>"
    depends_on:
      - database
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  web:
  database:
