version: "3"

services:
  # nginx:
  #   container_name: pluma-online-nginx
  #   build:
  #     context: ./nginx
  #     cache_from:
  #       - alpine:latest
  #       - fiubiorg/nginx:latest
  #     labels:
  #       com.pluma-nginx.description: "Custom NGINX container for PluMA Online"
  #       com.pluma-nginx.maintainer: "Joseph R. Quinn <quinn.josephr@protonmail.com>"
  #     args:
  #       - NGINX_VERSION=1.19.10
  #   image: fiubiorg/nginx:latest
  #   volumes:
  #     - web:/src/http
  #     - ./nginx/etc/nginx:/etc/nginx
  #     - ./nginx/server-configs-nginx/h5bp:/etc/nginx/h5bp
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: unless-stopped
  #   depends_on:
  #     - webapp

  database:
    container_name: pluma-online-database
    image: mongo:latest
    command: ["--keyFile", "/data/mongodb.key", "--replSet", "dbrs", "--bind_ip_all"]
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - web
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
      - ./docker/mongodb/init/01-mongo-init.sh:/docker-entrypoint-initdb.d/01-mongo-init.sh
      - ./docker/mongodb/mongodb.key:/data/mongodb.key
    restart: unless-stopped

  redis:
    container_name: pluma-online-redis
    image: redis:alpine
    networks:
      - web

  webapp:
    container_name: pluma-online-webapp
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "4200:4200"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      APP_HOST: ${APP_HOST}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      DATABASE_URL: ${DATABASE_URL}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}

volumes:
  web:
  database:

networks:
  web:
