version: "3.8"

services:
  nginx:
    container_name: pluma-nginx
    build:
      context: ./nginx
      cache_from:
        - alpine:latest
        - fiubiorg/nginx:latest
      labels:
        com.pluma-nginx.description: "Custom NGINX container for PluMA Online"
        com.pluma-nginx.maintainer: "Joseph R. Quinn <quinn.josephr@protonmail.com>"
      args:
        - NGINX_VERSION=1.19.10
    image: fiubiorg/nginx:latest
    volumes:
      - web:/src/http
      - ./nginx/etc/nginx:/etc/nginx
      - ./nginx/server-configs-nginx/h5bp:/etc/nginx/h5bp
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

  database:
    container_name: pluma-database
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    container_name: pluma-redis
    image: redis:alpine

volumes:
  web:

networks:
  web:
