// Copyright (c) 2019-2020 FIUBioRG
// SPDX-License-Identifier: MIT

//! Routes generated by yew-router

use yew_router::prelude::*;

///App routes
#[derive(Switch, Clone, PartialEq)]
pub enum AppRoute {
    #[to="/"]
    Index,
    #[to="/pluma"]
    Pluma(PlumaRoute),
}

/// PluMA routes
#[derive(Switch, Clone, PartialEq)]
pub enum PlumaRoute {
    #[to="/"]
    Index,
    #[to="/plugins"]
    Plugins,
    #[to="/pipelines"]
    Pipelines,
}
