FROM mongo:latest

COPY ./init/01-mongo-init.sh /docker-entrypoint-initdb.d/01-mongo-init.sh
COPY ./init/02-create-indexes.js /docker-entrypoint-initdb.d/02-create-indexes.js

RUN openssl rand -base64 756 > /data/mongodb.key && \
  chown mongodb:mongodb /data/mongodb.key && \
  chmod 0400 /data/mongodb.key && \
  chmod +x /docker-entrypoint-initdb.d/01-mongo-init.sh
