name: Containerize
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build the Docker image and push to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the image and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
          pull: true
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
